name: Japan
favicon: null
layout_spectrum: 0.506383
typography_spectrum: 0.7118201
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Lessons on Japan and Japanese life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2034048
  lightness: 0.799767
  saturation: 0.9956425
  rhythmicContrast: 0.5461788
purpose: []
