layout_spectrum: 0.9297507
typography_spectrum: 0.7118201
color:
  lightness: 0.799767
  brandStrength: 0.2034048
  saturation: 0.9956425
  rhythmicContrast: 0.5461788
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: Japan
