layout_spectrum: 0.7297872
name: Japan
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.2034048
  saturation: 0.9956425
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  lightness: 0.799767
  rhythmicContrast: 0.5461788
typography_spectrum: 0.7118201
